name: TestMbNetworkGo

on: [push]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Display Go version
        run: go version
      - name: Run Tests
        run: go test -v